#!/bin/bash
# Script for profit switching on miningpoolhub.com
# To be used with ccminer
# Will keep switching though ports until q is pressed
# Katie Rabbitt 01/01/2018

while true;
do 
profitMine(){

# set username and workername as variables so in the future only need to change 1 location
export USERNAME=yourusername
export WORKERNAME=yourworkername


# each line consists of executable, -r for retries of each line, -T timeout of 1 sec, 
# -a algorithm used, -o stratum port, -u variables, -d display devices
./ccminer -r 0 -T 1 -a groestl -o stratum+tcp://hub.miningpoolhub.com:12004 -u $USERNAME.$WORTKERNAME -d
./ccminer -r 0 -T 1 -a myr-gr -o stratum+tcp://hub.miningpoolhub.com:12005 -u $USERNAME.$WORKERNAME -d
./ccminer -r 0 -T 1 -a x11 -o stratum+tcp://hub.miningpoolhub.com:12007 -u $USERNAME.$WORKERNAME -d
./ccminer -r 0 -T 1 -a x13 -o stratum+tcp://hub.miningpoolhub.com:12008 -u $USERNAME.$WORKERNAME -d 
./ccminer -r 0 -T 1 -a x15 -o stratum+tcp://hub.miningpoolhub.com:12009 -u $USERNAME.$WORKERNAME -d 
./ccminer -r 0 -T 1 -a neoscrypt -o stratum+tcp://hub.miningpoolhub.com:12012 -u $USERNAME.$WORKERNAME -d
./ccminer -r 0 -T 1 -a qubit -o stratum+tcp://hub.miningpoolhub.com:12014 -u $USERNAME.$WORKERNAME -d
./ccminer -r 0 -T 1 -a quark -o stratum+tcp://hub.miningpoolhub.com:12015 -u $USERNAME.$WORKERNAME -d
./ccminer -r 0 -t 1 -a skein -o stratum+tcp://hub.miningpoolhub.com:12016 -u $USERNAME.$WORKERNAME -d
./ccminer -r 0 -T 1 -a lyra2v2 -o stratum+tcp://hub.miningpoolhub.com:12018 -u $USERNAME.$WORKERNAME -d
./ccminer -r 0 -T 1 -a vanilla -o stratum+tcp://hub.miningpoolhub.com:12019 -u $USERNAME.$WORKERNAME -d

}

profitMine

if [[ $input = "q" ]] || [[ $input = "Q" ]] 
        then break 
fi

done
